version: '3.7'

services:

    client:
        build:
            context: ./app-react
            dockerfile: Dockerfile-prod
        ports:
            - "3000:80"
        volumes: 
            - ./app-react:/app
            - /app/node_modules
        networks:
            - app-react

    mongodb:
        image: mongo
        container_name: mongocrudcontainer
        restart: unless-stopped
        command: mongod --auth
        environment:
            MONGO_INITDB_ROOT_USERNAME: "admin"
            MONGO_INITDB_ROOT_PASSWORD: "password"
            MONGO_INITDB_DATABASE: webapp
            MONGODB_DATA_DIR: /data/db
        volumes:
        - mongodbdata:/data/db
        networks:
        - api-python

    api:
        build: 
            context: ./api-python
            dockerfile: Dockerfile
        command: python app.py runserver 0.0.0.0:5000
        # command: gunicorn --bind 0.0.0.0:5000 app:app
        ports:
            - "5000:5000"
        environment:
            DB_HOST: mongodb
            DB_USERNAME: "apiuser"
            DB_PASSWORD: "apipassword"
        volumes:
            - appdata:/var/www/
        depends_on: 
            - mongodb
        networks:
            - app-react
            - api-python

networks:
    app-react:
        driver: bridge
    api-python:
        driver: bridge
volumes:
    mongodbdata:
        driver: local
    appdata:
        driver: local