PATH_LOG = 'log/'
FILE_LOG = 'newscrud.log'

ENVIRONMENT_PROD = 'PROD'
ENVIRONMENT_DEV = 'DEV'

REQUEST_SUCCESS = 'success'
REQUEST_ERROR = 'request_error'

# Status de sucesso:
STATUS_OK = 200
STATUS_CREATED = 201
STATUS_ACCEPTED = 202
STATUS_NO_CONTENT = 204
STATUS_RESET_CONTENT = 205

# Status de erro:
STATUS_BAD_REQUEST = 400
STATUS_FORBIDDEN = 403
STATUS_NOT_FOUND = 404
STATUS_INTERNAL_SERVER_ERROR = 500
