# Este arquivo é usado quando queremos usar um ambiente de produção.
# Para tanto, é necessário usar o comando:
#       docker-compose -f docker-compose-prod.yml up --build
# que indica este arquivo para construir a aplicação.

# Cria uma nova imagem baseada no nosso node:
FROM node:latest as build

# Configura o diretório de trabalho:
WORKDIR /app
ADD . /app

# Adiciona /app/node_modules/.bin às variáveis de ambiente:
ENV PATH /app/node_modules/.bin:$PATH

# Instala todas as dependências do app:
COPY package.json /app/package.json
RUN npm install

# Roda o Build (produção)
RUN npm run build

# Cria uma imagem do servidor nginx e faz deploy do app React recém construído
FROM nginx:1.17-alpine

COPY --from=build /app/build /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]